require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '10.0'

abstract_target 'mobilestacker' do
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'React-callinvoker', :path => "../node_modules/react-native/ReactCommon/callinvoker"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  pod 'RNOpenAppSettings', :path => '../node_modules/react-native-app-settings'

  pod 'react-native-cookies', :path => '../node_modules/react-native-cookies/ios'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'


  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-intercom', :path => '../node_modules/react-native-intercom'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNRate', :path => '../node_modules/react-native-rate'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'


  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-version-number', :path => '../node_modules/react-native-version-number'

  pod 'BugsnagReactNative', :path => '../node_modules/bugsnag-react-native'

  pod 'react-native-legit-story-share', :path => '../node_modules/react-native-legit-story-share'

  pod 'react-native-build-config', :path => '../node_modules/react-native-build-config'

  pod 'RNIap', :path => '../node_modules/react-native-iap'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'RNFBAnalytics', :path => '../node_modules/@react-native-firebase/analytics'

  pod 'RNFBDynamicLinks', :path => '../node_modules/@react-native-firebase/dynamic-links'
  
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'ReactNativeExceptionHandler', :path => '../node_modules/react-native-exception-handler'

  
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNAppleAuthentication', :path => '../node_modules/@invertase/react-native-apple-authentication'

  pod 'react-native-custom-tabs', :path => '../libs/react-native-custom-tabs'
  
  pod 'react-native-appearance', :path => '../node_modules/react-native-appearance'
  
  pod 'RNScreens', :path => '../node_modules/react-native-screens'
  
  pod 'react-native-simple-crypto', :path => '../node_modules/react-native-simple-crypto'
  
  pod 'react-native-webengage', :path => '../node_modules/react-native-webengage'
  
  target 'iDent' do
  end
  target 'Medstream' do
  end

  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
    end
  end
  
  use_native_modules!
end

target 'NotificationService' do
  platform :ios, '10.0'
  pod 'WebEngageBannerPush'
end

# ContentExtension Target
target 'NotificationViewController' do
  platform :ios, '10.0'
  pod 'WebEngageAppEx/ContentExtension'
end
